server:
  port: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: mytablemodule
          uri: lb://JAVACRUDBITIRME
          predicates:
            - Path=/api/**